### ISSUE TITLE
KeyError: "Registering two gradient with name 'BlockLSTM'! 

### ISSUE THREAD

**Issue by deepbluesea** [IBM/tensorflow-large-model-support#18]
`KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/registry.py:66)"`

**Comment by smatzek** [comment]
If you are experiencing an issue with TensorFlow Large Model Support, can you please supply more information?

**Comment by deepbluesea** [comment]
nvm fixed by downgraded tensorflow to 1.14.0

**Comment by Ordgod** [comment]
I meet the same issue even I use tensorflow 1.14.0.  Fully details are as follows:

`Using TensorFlow backend.
Traceback (most recent call last):
  File "train_ori_tflms.py", line 1, in <module>
    from keras import backend as K
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/keras/activations.py", line 6, in <module>
    from .engine import Layer
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 24, in <module>
    from .. import callbacks as cbks
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/keras/callbacks.py", line 26, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/rnn/__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_core/python/framework/registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register /exports/lkeb-hpc/jjia/software/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_core/python/framework/registry.py:66)"
`

**Comment by lpapenme** [comment]
Just for anybody else who reads this: this error occurs in cases where you import `tensorflow_core` instead of `tensorflow` in TensorFlow 2.x.

Even though `tensorflow_core` is eventually imported by `tensorflow`, you have to use `tensorflow`.

**Comment by mproszewska** [comment]
> Just for anybody else who reads this: this error occurs in cases where you import `tensorflow_core` instead of `tensorflow` in TensorFlow 2.x.
> 
> Even though `tensorflow_core` is eventually imported by `tensorflow`, you have to use `tensorflow`.

How to fix that? Calling `tf.sysconfig.get_lib()` returns path to `tensorflow_core` dir, but I'm not sure if this is a problem and if so, how to change that.

**Comment by 00001101-xt** [comment]
@mproszewska Have you found the solution to this issue?
