### ISSUE TITLE
Support for slim.learning?

### ISSUE THREAD

**Issue by samhodge** [IBM/tensorflow-large-model-support#2]
Hi

I would like to train a model that will not fit into GPU RAM using large model support.

But the model I would like to train uses:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py

The model is here:
https://github.com/tensorflow/models/blob/master/research/deeplab/train.py

What advice would you have for training this model with large model support?

sam

**Comment by smatzek** [comment]
TensorFlow Large Model Support does static analysis and modification of the graph so it shouldn't matter how the graph is constructed (low level APIs, Estimators, Keras, Slim, etc) for it to work as long as its inputs are provided and the modifications are done before the graph is run in a session.

I have not tried it with slim before but gave it a try with the 
https://github.com/tensorflow/models/blob/master/research/deeplab/train.py

model with the setup done via:
https://github.com/tensorflow/models/blob/master/research/deeplab/local_test.sh

Never having used SLIM before I had a bit of trouble finding the right place to put the gradients in a named scope (one of the required inputs to TFLMS).  In the end I dumped out the operation names to see where the gradients were and found they were under a 'gradients/' name scope.

So adding the following code to line ~368 of train.py did the trick:

```
    # Soft placement allows placing on CPU ops without GPU implementation.
    session_config = tf.ConfigProto(
        allow_soft_placement=True, log_device_placement=False)
    ops = [n.name for n in tf.get_default_graph().as_graph_def().node]
    print('Operations %s' % ops)
    from tensorflow_large_model_support import LMS
    lms = LMS({'gradients'}, graph=tf.get_default_graph())
    # When using clones do something like the following, for 4 clones.
    #lms = LMS({'clone_0/gradients', 'clone_1/gradients', 'clone_2/gradients', 'clone_3/gradients'}, graph=tf.get_default_graph())
    lms.run()
    # Start the training.
    slim.learning.train(
```

This output the following log segment:

```
INFO:tensorflow:[LMS][0] Edited model is valid and logically equivalent to the original one
INFO:tensorflow:[LMS][0] Added 1481 ops into the model
INFO:tensorflow:[LMS][0] Editing model for LMS, took: 96665.21167755127 ms
INFO:tensorflow:[LMS][0] 737 tensors will be swapped out(in) to(from) the host
```

Also note, I am running with a PowerAI build of TensorFlow so I did not do the config setting as described here:
https://github.com/IBM/tensorflow-large-model-support#tensorflow-grappler-and-tensorflow-large-model-support

I also did not push any of the scaling parameters of train.py to see if they would cause out of memory errors (OOMs) and then push beyond the OOMs with TFLMS.

The next steps would be to do this on a model that doesn't fit and then tune the `n_tensors` and `lb` parameters on the LMS class to achieve the best performance while fitting in memory.

**Comment by smatzek** [comment]
If you follow the README's performance tuning tips to have TFLMS find and report your graph starting ops, you can shave time off future graph modifications.

Specifying the starting ops as reported by TFLMS takes 46 seconds off the analysis time of this model.
```
    lms = LMS({'gradients'}, starting_op_names=['xception_65/entry_flow/conv1_1/weights/read'], graph=tf.get_default_graph())
```

```
INFO:tensorflow:[LMS][0] Editing model for LMS
INFO:tensorflow:[LMS][0] n_tensors: all tensors
INFO:tensorflow:[LMS][0] lb: 1
INFO:tensorflow:[LMS][0] Edited model is valid and logically equivalent to the original one
INFO:tensorflow:[LMS][0] Added 1481 ops into the model
INFO:tensorflow:[LMS][0] Editing model for LMS, took: 50093.54829788208 ms
INFO:tensorflow:[LMS][0] 737 tensors will be swapped out(in) to(from) the host
```

**Comment by samhodge** [comment]
Thanks 

I will try this out at the next opportunity.

Seems like exactly like the information I need.

Thanks again 

Sam

**Comment by smatzek** [comment]
When you have a chance to this out, please keep in touch and provide feedback, etc. My attempt at enabling TFLMS on this model was a quick attempt. There is likely room for improvement with further study of the model including better selection of the optimization scope(s) and possibly adding exclusion scopes.

Additionally, the model you reference is for 2D image segmentation. You may be interested in reading an in-depth case study of using TFLMS for 3D image segmentation using 3DUNet. It is online here and now also included in the citations section of the README:
https://developer.ibm.com/linuxonpower/2018/07/27/tensorflow-large-model-support-case-study-3d-image-segmentation/

Since I believe the initial question behind this issue has been answered I'm going to close this one out.

**Comment by samhodge** [comment]
It still OOMed

```

INFO:tensorflow:[LMS][0] Editing model for LMS
INFO:tensorflow:[LMS][0] n_tensors: all tensors
INFO:tensorflow:[LMS][0] lb: 1
INFO:tensorflow:[LMS][0] Edited model is valid and logically equivalent to the original one
INFO:tensorflow:[LMS][0] Added 917 ops into the model
INFO:tensorflow:[LMS][0] Editing model for LMS, took: 70587.35752105713 ms
INFO:tensorflow:[LMS][0] 455 tensors will be swapped out(in) to(from) the host
INFO:tensorflow:Initializing model from path: /work/models/research/deeplab/deeplabv3_cityscapes_train/model.ckpt
WARNING:tensorflow:From /opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py:737: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-12-02 20:05:52.760877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:05:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2018-12-02 20:05:52.760917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-12-02 20:05:53.087279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-02 20:05:53.087322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-12-02 20:05:53.087334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-12-02 20:05:53.087762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14849 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0004:05:00.0, compute capability: 7.0)
INFO:tensorflow:Restoring parameters from /work/models/research/deeplab/deeplabv3_cityscapes_train/model.ckpt
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /work/models/research/deeplab/logs/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 0.
2018-12-02 20:06:40.791794: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 305.19MiB.  Current allocation summary follows.
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'decoder/decoder_conv0_depthwise/BatchNorm/FusedBatchNorm', defined at:
  File "deeplab/train.py", line 401, in <module>
    tf.app.run()
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/train.py", line 278, in main
    clones = model_deploy.create_clones(config, model_fn, args=model_args)
  File "/work/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "deeplab/train.py", line 207, in _build_deeplab
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)
  File "/work/models/research/deeplab/model.py", line 291, in multi_scale_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/work/models/research/deeplab/model.py", line 528, in _get_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/work/models/research/deeplab/model.py", line 630, in refine_by_decoder
    scope='decoder_conv0')
  File "/work/models/research/deeplab/core/utils.py", line 76, in split_separable_conv2d
    scope=scope + '_depthwise')
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2821, in separable_convolution2d
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 650, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 158, in call
    return super(BatchNormalization, self).call(inputs, training=training)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 514, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 401, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 51, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 398, in _fused_batch_norm_inference
    data_format=self._data_format)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 909, in fused_batch_norm
    name=name)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3465, in _fused_batch_norm
    is_training=is_training, name=name)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,304,513,513] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: decoder/decoder_conv0_depthwise/BatchNorm/FusedBatchNorm = FusedBatchNorm[T=DT_FLOAT, data_format="NCHW", epsilon=1.001e-05, is_training=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](decoder/decoder_conv0_depthwise/depthwise, decoder/decoder_conv0_depthwise/BatchNorm/gamma/read/_3695, decoder/decoder_conv0_depthwise/BatchNorm/beta/read/_3697, decoder/decoder_conv0_depthwise/BatchNorm/moving_mean/read/_3699, decoder/decoder_conv0_depthwise/BatchNorm/moving_variance/read/_3701)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: gradients/xception_65/exit_flow/block1/unit_1/xception_module/separable_conv1_depthwise/depthwise_grad/DepthwiseConv2dNativeBackpropFilter/_4607 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4656_...propFilter", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Traceback (most recent call last):
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,304,513,513] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: decoder/decoder_conv0_depthwise/BatchNorm/FusedBatchNorm = FusedBatchNorm[T=DT_FLOAT, data_format="NCHW", epsilon=1.001e-05, is_training=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](decoder/decoder_conv0_depthwise/depthwise, decoder/decoder_conv0_depthwise/BatchNorm/gamma/read/_3695, decoder/decoder_conv0_depthwise/BatchNorm/beta/read/_3697, decoder/decoder_conv0_depthwise/BatchNorm/moving_mean/read/_3699, decoder/decoder_conv0_depthwise/BatchNorm/moving_variance/read/_3701)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: gradients/xception_65/exit_flow/block1/unit_1/xception_module/separable_conv1_depthwise/depthwise_grad/DepthwiseConv2dNativeBackpropFilter/_4607 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4656_...propFilter", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deeplab/train.py", line 401, in <module>
    tf.app.run()
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/train.py", line 394, in main
    save_interval_secs=FLAGS.save_interval_secs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 770, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,304,513,513] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: decoder/decoder_conv0_depthwise/BatchNorm/FusedBatchNorm = FusedBatchNorm[T=DT_FLOAT, data_format="NCHW", epsilon=1.001e-05, is_training=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](decoder/decoder_conv0_depthwise/depthwise, decoder/decoder_conv0_depthwise/BatchNorm/gamma/read/_3695, decoder/decoder_conv0_depthwise/BatchNorm/beta/read/_3697, decoder/decoder_conv0_depthwise/BatchNorm/moving_mean/read/_3699, decoder/decoder_conv0_depthwise/BatchNorm/moving_variance/read/_3701)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: gradients/xception_65/exit_flow/block1/unit_1/xception_module/separable_conv1_depthwise/depthwise_grad/DepthwiseConv2dNativeBackpropFilter/_4607 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4656_...propFilter", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'decoder/decoder_conv0_depthwise/BatchNorm/FusedBatchNorm', defined at:
  File "deeplab/train.py", line 401, in <module>
    tf.app.run()
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/train.py", line 278, in main
    clones = model_deploy.create_clones(config, model_fn, args=model_args)
  File "/work/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "deeplab/train.py", line 207, in _build_deeplab
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)
  File "/work/models/research/deeplab/model.py", line 291, in multi_scale_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/work/models/research/deeplab/model.py", line 528, in _get_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/work/models/research/deeplab/model.py", line 630, in refine_by_decoder
    scope='decoder_conv0')
  File "/work/models/research/deeplab/core/utils.py", line 76, in split_separable_conv2d
    scope=scope + '_depthwise')
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2821, in separable_convolution2d
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 650, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 158, in call
    return super(BatchNormalization, self).call(inputs, training=training)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 514, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 401, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 51, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 398, in _fused_batch_norm_inference
    data_format=self._data_format)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 909, in fused_batch_norm
    name=name)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3465, in _fused_batch_norm
    is_training=is_training, name=name)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,304,513,513] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: decoder/decoder_conv0_depthwise/BatchNorm/FusedBatchNorm = FusedBatchNorm[T=DT_FLOAT, data_format="NCHW", epsilon=1.001e-05, is_training=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](decoder/decoder_conv0_depthwise/depthwise, decoder/decoder_conv0_depthwise/BatchNorm/gamma/read/_3695, decoder/decoder_conv0_depthwise/BatchNorm/beta/read/_3697, decoder/decoder_conv0_depthwise/BatchNorm/moving_mean/read/_3699, decoder/decoder_conv0_depthwise/BatchNorm/moving_variance/read/_3701)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: gradients/xception_65/exit_flow/block1/unit_1/xception_module/separable_conv1_depthwise/depthwise_grad/DepthwiseConv2dNativeBackpropFilter/_4607 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4656_...propFilter", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```


here is the run script

```
python deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=90000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size=2049 \
    --train_crop_size=2049 \
    --train_batch_size=1 \
    --fine_tune_batch_norm=false \
    --dataset="cityscapes" \
    --tf_initial_checkpoint=${PWD}/deeplab/deeplabv3_cityscapes_train/model.ckpt \
    --train_logdir=${PWD}/deeplab/logs \
    --dataset_dir=${PWD}/deeplab/datasets/cityscapes/tfrecord/
```

I might try adjusting the dimensions until it no longer dies and OOM death.


UPDATE:

works OK with

    --train_crop_size=2049 \
    --train_crop_size=1025 \

**Comment by smatzek** [comment]
Thanks for following up.

Out of curiosity, what is the breaking point without LMS? What resolution can you get with/without it?

A few other observations:
Your output shows "455 tensors will be swapped" and mine above shows "737 tensors will be swapped". This may be due to different code levels (different model commit level or different TF level).  I was using an RC build of TF 1.12. Did you specify starting_op_names ?

**Comment by samhodge** [comment]
No starting op names were specified.  Using TF 1.10
