### ISSUE TITLE
model support with LMSKerasCallback on yolo

### ISSUE THREAD

**Issue by michalkowalski94** [IBM/tensorflow-large-model-support#9]
I've got a problem with toposort in large-model-support
`Using TensorFlow backend.
INFO:tensorflow:[LMS][0] Editing model for LMS
INFO:tensorflow:[LMS][0] n_tensors: all tensors
INFO:tensorflow:[LMS][0] lb: 1
Create YOLOv3 model with 9 anchors and 3 classes.
Train on 6103 samples, val on 678 samples, with batch size 1.
Traceback (most recent call last):
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/lms_train.py", line 216, in <module>
    _main()
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/lms_train.py", line 88, in _main
    callbacks=[logging, checkpoint, lms])
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 94, in fit_generator
    callbacks.set_model(callback_model)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/callbacks.py", line 54, in set_model
    callback.set_model(model)
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/tensorflow_large_model_support/lms.py", line 957, in set_model
    lmsMod.run()
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/tensorflow_large_model_support/lms.py", line 336, in run
    self._topo_sort.build()
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/tensorflow_large_model_support/topos.py", line 45, in build
    topo_sort = list(toposort.toposort(self._build_dependency_dict()))
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/toposort.py", line 81, in toposort
    raise CircularDependencyError(data)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/toposort.py", line 45, in __init__
    s = 'Circular dependencies exist among these items: {{{}}}'.format(', '.join('{!r}:{!r}'.format(key, value) for key, value in sorted(data.items())))
TypeError: '<' not supported between instances of 'Operation' and 'Operation'`

I'm using this code
https://pastebin.com/Nut6Ss3n

**Comment by smatzek** [comment]
Thanks for submitting this issue. The exact error you are getting is actually an error in while trying to generate an error message in toposort, which is a separate package from tensorflow-large-model-support.

Toposort is used sort the nodes in the model graph to know more about dependencies and the distance between two nodes.  Toposort is saying the yolo model has circular dependencies among some of its nodes and is trying to throw an error for that.

We haven't seen this behavior with other models we've looked at.

I have recreated this error and we are continuing to look into it. I am using the VOC2007 dataset to recreate have thus reverted some of the changes you made to https://github.com/qqwweee/keras-yolo3/blob/master/train.py.

When I remove `lms` from the callback list and run on a 32GB GPU I get the following error, which I think is related to your other changes:

```
Epoch 1/40
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    _main()
  File "train.py", line 89, in _main
    callbacks=[logging, checkpoint, ])
  File ".../lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File ".../lib/python3.6/site-packages/keras/engine/training.py", line 2230, in fit_generator
    class_weight=class_weight)
  File ".../lib/python3.6/site-packages/keras/engine/training.py", line 1877, in train_on_batch
    class_weight=class_weight)
  File ".../lib/python3.6/site-packages/keras/engine/training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File ".../lib/python3.6/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (None, None, 1) but got array with shape (2048, 2048, 3)
```

**Comment by michalkowalski94** [comment]
Thank You for pointing my problem with generator, I have must modified wrong version of code. I'll try to run in once again with changes to genertor and see if it helps.

EDIT:
Everything with my [generator is allright](https://github.com/michalkowalski94/MSADnn/blob/master/keras_darknet_yolo3/yolo3/utils.py). I just hadn't pushed it yet to my github to this time.  After running it without LMSKerasCallback i recieve this message. Please try with that modified generator.
`Traceback (most recent call last):
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/lms_train.py", line 215, in <module>
    _main()
  File "/net/scratch/people/plgmkowalski94/master/new/keras-yolo3/lms_train.py", line 87, in _main
    callbacks=[logging, checkpoint]) #, lms])
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/net/people/plgmkowalski94/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,512,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node conv2d_39/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/conv2d_39/convolution_grad/Conv2DBackpropInput"], data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](leaky_re_lu_38/LeakyRelu, conv2d_39/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.`

**Comment by smatzek** [comment]
After investigating this more, there is not a straight forward way to fix this issue. The model uses a while loop which injects cycles into the graph. Since toposort does not support cyclic graphs and TensorFlow Large Model Support (TFLMS) depends on toposort the options available would be to remove the toposort dependency or exclude the cyclic part of the graph from the analysis, neither of which are quick fixes.

Unfortunately what this means is that for the time being, TFLMS only supports models that create directed acyclic graphs.

**Comment by Dakror** [comment]
I'm experiencing the same issue using a seq2seq model using the corresponding tensorflow contrib module. There are cyclic dependencies within (amongst others) the BasicDecoder according to toposort.

**Comment by smatzek** [comment]
Models with cycling dependencies are now supported with TensorFlow Large Model Support for TensorFlow 2 (currently in the master branch level of this repository.)
